#数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true # Enable template caching.
    enabled: true # Enable Thymeleaf view resolution for Web frameworks.
  messages:
    basename: messages
  application:
    name: spring-boot-redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000



#mybatis
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true
    #查询时,关闭关联对象及时加载以提高性能
    lazy-loading-enabled: false
    #按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    aggressive-lazy-loading: false
    #允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #对于批量更新操作缓存SQL以提高性能
    default-executor-type: REUSE
    #数据库执行超时时间
    default-statement-timeout: 25000


#actuator属性设置
#management:
#  endpoints:
#    #web: exposure:        include: *
#    actuator:
#      enabled: true
#

server:
  port: 8080

application:
  version: 1.0

spring-boot:
  version: 2.0.3.RELEASE


demo:
  id: "1"
  name: "hello"
  property: "prop"